module.exports = {
    COMMUNITY_CHAT:"COMMUNITY_CHAT",

    // user
    USER_CONNECTED:"USER_CONNECTED",
    USER_DISCONNECTED:"USER_DISCONNECTED",
    VERIFY_USER:"VERIFY_USER",

    // message
    MESSAGE_SENT:"MESSAGE_SENT",
    MESSAGE_RECEIVED:"MESSAGE_RECEIVED",
    PRIVATE_MESSAGE:"PRIVATE_MESSAGE",

    // state
    TYPING:"TYPING",
    LOGOUT:"LOGOUT",
};